services:
  siithub-gitserver:
    image: gitserver
    restart: always
    volumes:
      - ./git-server-data/repos:/home
    ports:
      - "3002:80"
      - "3022:22"
    environment:
      PORT: 80
      ACCESS_KEY: AKIAQVU4V4B5H5YSLC7Y
      SECRET_ACCESS_KEY: x
      REGION: eu-central-1
      QUEUE_URL: https://sqs.eu-central-1.amazonaws.com/046499487866/siithub-queue

  mongo:
    image: mongo
    container_name: mongo_db
    restart: always
    volumes:
      - ./mongo-data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: password
